[build]
  publish = "/"
  command = ""
  functions = "netlify/functions"

[dev]
  framework = "#static"
  functions = "netlify/functions"

# Redirect API requests to the Netlify function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
